### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by catap** [stanislaw/posix-macos-addons#52]
Is it possible to make license clear? This code is linking staticly with applications and it can cause license hell.

**Comment by stanislaw** [comment]
Normally, I would put Apache 2, however the `mqueue`-related code is taken from the book about Linux and the first `semaphore.h` implementation is taken from StackOverflow. Do you know how such a "hybrid" source code should be licenced?

You are the first one to treat this project as a real library so I have never considered the this project's license question before 😄

**Comment by catap** [comment]
The reason to ask it because I've created a port for this code: https://github.com/macports/macports-ports/pull/12331 :)

I needed it to build ecgen: https://github.com/macports/macports-ports/pull/12335

So, about license.
 1. code from a book — you mean that you read some book and retype everything? have you changed this code? how much?
 2. same here — how big your changes after copy and paste?

I feel that you may call it as Apache 2 but also write a notice with explain the source of some part of work.

**Comment by stanislaw** [comment]
> I needed it to build ecgen: macports/macports-ports#12335

May I ask which of the functions are you using there?

**Comment by catap** [comment]
> May I ask which of the functions are you using there?

Part of my personal research. Some results are public available, if you interesting I can share some details, but I'd like to do it by more private communication... like email ;)

**Comment by stanislaw** [comment]
> > May I ask which of the functions are you using there?
> 
> Part of my personal research. Some results are public available, if you interesting I can share some details, but I'd like to do it by more private communication... like email ;)

Don't worry, I am only asking which functions of the `posix-macos-addons` are you using? I am asking because not all of them are equally tested and reliable.

**Comment by catap** [comment]
ah, here the code for which I've used it: https://github.com/J08nY/ecgen/pull/13

For me it just way to build it :)

**Comment by catap** [comment]
And thanks to make things clear. I hope in few days port with your library will be available for all macport's users.
