### ISSUE TITLE
Backport to 10.12 and down?

### ISSUE THREAD

**Issue by catap** [stanislaw/posix-macos-addons#54]
porting it to MacPorts allows to test this library on many differences versions and right now it discoveres some incompatibility with macOS 10.12 and before. Let me share the links to build log which contains errors:
 - https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/159228/steps/install-port/logs/stdio
 - https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/154308/steps/install-port/logs/stdio
 - https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/155661/steps/install-port/logs/stdio
 - https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/73537/steps/install-port/logs/stdio
 - https://build.macports.org/builders/ports-10.6_i386-builder/builds/40033/steps/install-port/logs/stdio

**Comment by stanislaw** [comment]
@catap I don't need the library to work on older macOS versions but I would be happy to support this effort.

I don't have access to these environments at home, so I am wondering how the MacPorts maintainers develop and debug against those older Mac machines? Looking at the build logs, the issues seem to be rather trivial but one definitely needs a way to run through those build jobs several times until they get green.

**Comment by catap** [comment]
@stanislaw personally I'm using virtualbox for such tasks :) It is possible to run on modern macbook via virtual box old macOS. You may download old distributives from apple: https://support.apple.com/en-us/HT211683

Also, some macport's maintainers is using old macOS.

**Comment by catap** [comment]
This also can be used: https://github.com/phracker/MacOSX-SDKs

**Comment by catap** [comment]
Well, it will be much more complicated than simple `ifdef`. `clock_gettime` was introduced at `10.12`

**Comment by catap** [comment]
Build are faild:
```
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_posix-macos-addons/posix-macos-addons/work/posix-macos-addons-cecae59732ed3998440cbe8dc7dd931281166141/src/time/posix-macos-time.c:10:10: fatal error: 'kern/clock.h' file not found
#include <kern/clock.h>
         ^
1 error generated.
```

I guess this issue should be reopened.

:(

**Comment by stanislaw** [comment]
Which version produces this?

**Comment by stanislaw** [comment]
With your latest PR, it looks getting closer to building with no errors though. Is it only missing one extra ifdef?

**Comment by catap** [comment]
Yes, this was the last master aka cecae59732ed3998440cbe8dc7dd931281166141.

The root cause of issue is much deeper that simple missed `ifdef`. It can't find headers because it is a part `Kernel.framework`.

Naive approach like
```
--- src/time/CMakeLists.txt
+++ src/time/CMakeLists.txt
@@ -1,5 +1,10 @@
+find_library(KERNEL_FRAMEWORK_LIBRARY Kernel)
+find_path(KERNEL_FRAMEWORK_INCLUDE_DIR "kern/clock.h")
+
 add_library(posix-macos-time posix-macos-time.c)
-target_include_directories(posix-macos-time PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
+target_include_directories(posix-macos-time PUBLIC ${CMAKE_CURRENT_SOURCE_DIR} PRIVAT ${KERNEL_FRAMEWORK_INCLUDE_DIR})
+
+target_link_libraries(posix-macos-time ${KERNEL_FRAMEWORK_LIBRARY})
 
 install(TARGETS posix-macos-time)
 install(FILES posix-macos-time.h TYPE INCLUDE)
```
fixed this issues, and opens a new one with `errno`: https://github.com/stanislaw/posix-macos-addons/runs/3719912288 on modern macOS => which seems like a big sign that something very bad happened.

The only way to fix it which I see is to buy some old mac mini and try it on this :)

**Comment by stanislaw** [comment]
I think I have found an easy way to test multiple versions. I am downloading the SDKs from https://github.com/phracker/MacOSX-SDKs to the `/Library/Developer/CommandLineTools/SDKs/` folder and then I select the framework using 

```cmake
set(CMAKE_OSX_SYSROOT /Library/Developer/CommandLineTools/SDKs/MacOSX10.9.sdk)
```

Doing this helped me to analyze your implementation of `clock_gettime`: it looks like it is linking to `Kernel.framework` which use by the user space applications is discouraged.

I went to look for a quick stub and found this https://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x thread with a number of answers whose authors are fighting with each other for the most portable and performant solution. At this point, we can go two ways:

1) Easy solution would be to some solution like the one I have in my branch. It compiles on all versions starting starting from 10.9. If we don't care much the underlying behavior, we can just merge it with a warning left.

2) The hard way would be to analyze all of those suggested implementations and write unit tests that make sure that the `clock_gettime` function is actually implementing the behavior of https://linux.die.net/man/3/clock_gettime at least for the REALTIME and MONOTONIC clocks. Would you be up for this challenge?

My branch:
https://github.com/stanislaw/posix-macos-addons/compare/macos-10.9?expand=1

**Comment by stanislaw** [comment]
The reason I am choosing 10.9 is because it is the lowest version that compiles the C++ stuff in Google Test properly. To be honest I don't really think we have to go lower than 10.9 because that's already quite ok.

**Comment by catap** [comment]
@stanislaw I can try to find some time to implement tests it in couple of months, not early. So, let try to find who first can do it :)

From another hand I'm starting to looking for old mac mini to buy it to use as test server with something old, like Lion to try it on real machine.

Regarding code: I think that the old API with `host_get_clock_service` should work the same way on modern macOS, so, testing it shouldn't be so hard.

**Comment by stanislaw** [comment]
This article looks quite great on explaining the details: https://dshil.github.io/blog/missed-os-x-clock-guide/.

**Comment by catap** [comment]
@stanislaw I have no idea about license issue, but it seems that you may easy to use apple's code here: https://opensource.apple.com/source/Libc/Libc-1439.141.1/gen/clock_gettime.c.auto.html

**Comment by stanislaw** [comment]
> @stanislaw I have no idea about license issue, but it seems that you may easy to use apple's code here: https://opensource.apple.com/source/Libc/Libc-1439.141.1/gen/clock_gettime.c.auto.html

It's actually a good idea. I don't think there is a problem as long as we, again, mention the source.

**Comment by catap** [comment]
@stanislaw after fast reading https://opensource.apple.com/source/Libc/Libc-1439.141.1/APPLE_LICENSE.auto.html it seems that you may use this code.

But I suggest to make it as separated sub-project and put license notice inside `.c` file.

**Comment by stanislaw** [comment]
However,

```
/Users/stanislaw/workspace/projects/code/posix-macos-addons/src/time/posix-macos-time.c:46:10: fatal error: 'os/base_private.h' file not found
#include <os/base_private.h>
         ^~~~~~~~~~~~~~~~~~~
```

**Comment by stanislaw** [comment]
Looks like it needs a bit more digging 😄

**Comment by catap** [comment]
@stanislaw this is a systemcall. Can you try to add `#include <mach/mach_time.h>`?

**Comment by stanislaw** [comment]
> @stanislaw this is a systemcall. Can you try to add `#include <mach/mach_time.h>`?

It's already added. The error is still there.

**Comment by stanislaw** [comment]
I have merged that for the time being. As I mentioned before, the lowest target should be 10.9 now.

**Comment by catap** [comment]
@stanislaw here some thoughts: https://github.com/stanislaw/posix-macos-addons/pull/60

**Comment by catap** [comment]
I'd like to share also this project: https://github.com/macports/macports-legacy-support

**Comment by stanislaw** [comment]
Please feel free to open a PR that adds it to the README where the other similar projects are listed.

**Comment by catap** [comment]
FYI: with blacklisting unsuported compiler macPorts has this library up to Snow Leopard: https://ports.macports.org/port/posix-macos-addons/details/
